const CONSTS = {
  ADD_FIELD: "ADD_FIELD",
  ADD_FIELD_CHOICE: "ADD_FIELD_CHOICE",
  ADD_FORM_ID: "ADD_FORM_ID",
  CHANGE_FIELD_CHOICE: "CHANGE_FIELD_CHOICE",
  CHANGE_FIELD_PROPERTY: "CHANGE_FIELD_PROPERTY",
  CHANGE_FORM_PROPERTY: "CHANGE_FORM_PROPERTY",
  CLEAR_FORM: "CLEAR_FORM",
  DELETE_FIELD: "DELETE_FIELD",
  ERROR: "ERROR",
  FOCUS_ON_FIELD: "FOCUS_ON_FIELD",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REPOSITION_FIELD: "REPOSITION_FIELD",
  SET_FORM: "SET_FORM",
  SET_FORMS: "SET_FORMS"
};

module.exports = CONSTS;
