const CONSTS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ERROR: "ERROR",
  ADD_FIELD: "ADD_FIELD",
  REPOSITION_FIELD: "REPOSITION_FIELD",
  FOCUS_ON_FIELD: "FOCUS_ON_FIELD"
};

module.exports = CONSTS;
