const CONSTS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ERROR: "ERROR",
  ADD_FIELD: "ADD_FIELD",
  REPOSITION_FIELD: "REPOSITION_FIELD",
  FOCUS_ON_FIELD: "FOCUS_ON_FIELD",
  CHANGE_FORM_PROPERTY: "CHANGE_FORM_PROPERTY",
  CHANGE_FIELD_PROPERTY: "CHANGE_FIELD_PROPERTY"
};

module.exports = CONSTS;
